gText_Birch_Welcome::
	.string "Champion!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "You may not recognize me, but it\n"
	.string "is I, KHADGAR, occupying a kindred\p"
	.string "soul's body from this world.\p"
	.string "This body is PROFESSOR BIRCH,\n"
	.string "But everyone here calls me the\p"
	.string "POKéMON PROFESSOR.\p"
	.string "I left this holographic message to\n"
	.string "help orient the Champions of Azeroth\p"
	.string "$"


gText_Birch_Pokemon::
	.string "This is what is called a \p"
	.string "“POKéMON.”\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In case the rift affected your\n"
	.string "memories, I'll catch you up quickly.\p"
	.string "So pay attention!\p"
	.string "As we made progress towards reaching\n"
	.string "our slumbering World Soul, Azeroth,\p"
	.string "Suddenly, a large rift appeared!\n"
	.string "We do not know what caused it, but\p"
	.string "Azeroth's being was sucked in, and\n"
	.string "out of the rift came pouring these\p"
	.string "odd, yet powerful creatures\p"
	.string "Fearlessly, I, and other Champions\n"
	.string "of Azeroth jumped in to find her.\p"
	.string "We found this world widely inhabited\n"
	.string "by these creatures, known as POKéMON.\p"
	.string "Here, humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, band together\n"
	.string "and battle others like them.\p"
	.string "We will need to leverage their power\n"
	.string "and companionship to traverse this\p"
	.string "unfamiliar world and mend the rift.\p"
	.string "To do this, you yourself will merge\n"
	.string "with a kindred soul and their body.\p"

	

gText_Birch_AndYouAre::
	.string "So, tell me about yourself!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "Remember, we are a bit under-cover.\n"
	.string "You, I, and other Champions will have\p"
	.string "to be careful not to scare the locals!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where adventure,\l"
	.string "and the fate of both our worlds await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
